### ISSUE TITLE
Docker install does not appear to work

### ISSUE THREAD

**Issue by hschenk** [di2e/openstorefront#1501]
I attempted to install the docker image as per the instructions, but it does not appear that the repo exists.  Has there been any changes recently that would prevent this?

**Comment by dshurt** [comment]
We are aware of some issues the docker images..  It's fairly new and it not our typically deploy mechanism.  However, we would like to get it up and running.  We are currently wrapping up the 2.2 release so, we can add fixing this to next release especially if we know there is some interest there.

**Comment by dshurt** [comment]
Update:

We have fixed the docker images and create images for 2.1 and 2.2.  We'll support future releases going forward.    Documentation is still in the works for 2.3.  However, you can install the images from https://hub.docker.com/r/flammablefork/openstorefront/  We are also providing a test data set as part 2.3.  You can get a sample data set from the develop branch currently,
